[package]
name = "kpm"
version = "1.0.0"
authors = ["Chris Olstrom <chris@olstrom.com>"]
edition = "2018"
license = "MIT"
description = "a program to audit or enforce kernel parameter values"

[dependencies]
env_logger = "^0.8"
log = "^0.4"
structopt = "^0.3"
sysctl = "^0.4"
